"""Dataset encoding workflow for the built-in tokenizer formats."""

from __future__ import annotations

import json
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Literal

import numpy as np
import pyarrow as pa
import pyarrow.ipc as pa_ipc

from tlg.tokenizers_learned import LearnedTokenizer
from tlg.tokenizer_io import CorpusSample


class EncodingError(RuntimeError):
    """Raised when encoding fails."""


@dataclass(frozen=True)
class EncodeConfig:
    tokenizer_path: Path
    input_paths: list[Path]
    text_key: str
    output_path: Path
    output_format: Literal["arrow", "npz"]
    max_length: int
    pad_to_max_length: bool
    prepend_bos: bool
    append_eos: bool
    write_maps: bool


@dataclass
class EncodeResult:
    output_path: Path
    report_path: Path
    metrics: dict[str, float]
    manifest: dict[str, object]
    artifacts: dict[str, str]


@dataclass
class _Encoding:
    ids: list[int]


class _BpeRuntimeTokenizer:
    def __init__(self, vocab: dict[str, int], merges: list[list[str]], special_tokens: list[str]) -> None:
        tokenizer = LearnedTokenizer(
            name="loaded",
            vocab=vocab,
            merges=[tuple(pair) for pair in merges],
            lowercase=False,
            unicode_normalize=None,
            tokenizer_hash="",
            unk_token=_find_special_token(special_tokens, {"<unk>", "<unknown>"}) or "<unk>",
        )
        self.tokenizer = tokenizer
        self.vocab = vocab
        self.special_tokens = special_tokens
        self._id_to_token = {idx: token for token, idx in vocab.items()}

    def encode(self, text: str) -> _Encoding:
        _, ids = self.tokenizer.encode_with_ids(text)
        return _Encoding(ids)

    def token_to_id(self, token: str) -> int:
        return self.tokenizer.token_to_id(token)

    def id_to_token(self, idx: int) -> str:
        return self._id_to_token.get(idx, "")

    def get_vocab(self) -> dict[str, int]:
        return dict(self.vocab)


class _UnigramRuntimeTokenizer:
    def __init__(self, vocab: dict[str, int], special_tokens: list[str]) -> None:
        self.vocab = vocab
        self.special_tokens = special_tokens
        self._id_to_token = {idx: token for token, idx in vocab.items()}
        self.unk_id = self.vocab.get(_find_special_token(special_tokens, {"<unk>", "<unknown>"}) or "<unk>", 0)

    def encode(self, text: str) -> _Encoding:
        tokens = text.split()
        ids = [self.vocab.get(token, self.unk_id) for token in tokens]
        return _Encoding(ids)

    def token_to_id(self, token: str) -> int:
        return self.vocab.get(token, self.unk_id)

    def id_to_token(self, idx: int) -> str:
        return self._id_to_token.get(idx, "")

    def get_vocab(self) -> dict[str, int]:
        return dict(self.vocab)


class LoadedTokenizer:
    """Loader for tokenizer artifacts generated by :mod:`tlg.tokenizer_training`."""

    def __init__(self, tokenizer_path: Path) -> None:
        self.tokenizer_path = tokenizer_path
        self._runtime = self._load_runtime(tokenizer_path)
        self.vocab = self._runtime.get_vocab()
        self.special_tokens = self._metadata.get("special_tokens", [])
        self.unk_id = self.token_to_id(_find_special_token(self.special_tokens, {"<unk>", "<unknown>"}) or "<unk>")
        pad_token = _find_special_token(self.special_tokens, {"<pad>", "<padding>"})
        bos_token = _find_special_token(self.special_tokens, {"<bos>", "<s>"})
        eos_token = _find_special_token(self.special_tokens, {"<eos>", "</s>"})
        self.pad_id = self.token_to_id(pad_token) if pad_token else None
        self.bos_id = self.token_to_id(bos_token) if bos_token else None
        self.eos_id = self.token_to_id(eos_token) if eos_token else None

    def _load_runtime(self, tokenizer_path: Path):
        if tokenizer_path.suffix not in {".json", ".model"}:
            raise EncodingError(f"Unsupported tokenizer file: {tokenizer_path}")
        try:
            data = json.loads(tokenizer_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:  # pragma: no cover - defensive
            raise EncodingError(f"Invalid tokenizer file: {tokenizer_path}") from exc

        fmt = data.get("format")
        self._metadata = data.get("metadata", {})
        special_tokens = self._metadata.get("special_tokens", [])

        if fmt == "toy-bpe":
            merges = data.get("merges", [])
            vocab = {token: int(idx) for token, idx in data.get("vocab", {}).items()}
            return _BpeRuntimeTokenizer(vocab, merges, special_tokens)
        if fmt == "toy-unigram":
            vocab = {token: int(idx) for token, idx in data.get("vocab", {}).items()}
            return _UnigramRuntimeTokenizer(vocab, special_tokens)
        raise EncodingError("Unsupported tokenizer format")

    def encode(self, text: str) -> _Encoding:
        return self._runtime.encode(text)

    def token_to_id(self, token: str | None) -> int | None:
        if token is None:
            return None
        return self._runtime.token_to_id(token)

    def id_to_token(self, idx: int) -> str:
        return self._runtime.id_to_token(idx)


def encode_dataset(config: EncodeConfig, tokenizer: LoadedTokenizer, corpus: Iterable[CorpusSample]) -> EncodeResult:
    samples = [sample for sample in corpus]
    if not samples:
        raise EncodingError("No samples found for encoding")

    if config.pad_to_max_length and tokenizer.pad_id is None:
        raise EncodingError("pad_to_max_length requires <pad> token")

    start = time.perf_counter()
    encoded_sequences: list[list[int]] = []
    attention_masks: list[list[int]] = []
    lengths: list[int] = []
    unk_tokens = 0
    total_tokens = 0

    for sample in samples:
        encoding = tokenizer.encode(sample.text)
        ids = list(encoding.ids)
        if config.prepend_bos and tokenizer.bos_id is not None:
            ids.insert(0, tokenizer.bos_id)
        if config.append_eos and tokenizer.eos_id is not None:
            ids.append(tokenizer.eos_id)

        truncated = ids[: config.max_length]
        attention = [1] * len(truncated)
        if config.pad_to_max_length and tokenizer.pad_id is not None:
            padding = config.max_length - len(truncated)
            if padding > 0:
                truncated.extend([tokenizer.pad_id] * padding)
                attention.extend([0] * padding)

        encoded_sequences.append(truncated)
        attention_masks.append(attention)
        effective_length = sum(attention)
        lengths.append(int(effective_length))
        total_tokens += int(effective_length)
        unk_tokens += sum(1 for idx, mask in zip(truncated, attention) if mask and idx == tokenizer.unk_id)

    elapsed = max(time.perf_counter() - start, 1e-9)

    report = {
        "samples": float(len(samples)),
        "avg_tokens": float(np.mean(lengths)),
        "p95_tokens": float(np.percentile(lengths, 95)),
        "encode_time_sec": elapsed,
        "encode_throughput_samples_per_sec": len(samples) / elapsed,
        "unk_rate": (unk_tokens / total_tokens) if total_tokens else 0.0,
    }

    config.output_path.parent.mkdir(parents=True, exist_ok=True)

    if config.output_format == "npz":
        np.savez_compressed(
            config.output_path,
            input_ids=np.asarray(encoded_sequences, dtype=np.int32),
            attention_mask=np.asarray(attention_masks, dtype=np.int8),
            lengths=np.asarray(lengths, dtype=np.int32),
        )
    else:
        _write_arrow(config.output_path, encoded_sequences, attention_masks, lengths, samples)

    report_path = config.output_path.with_suffix(".report.json")
    report_path.write_text(json.dumps(report, indent=2), encoding="utf-8")

    artifacts = {
        "encoded": str(config.output_path),
        "report": str(report_path),
    }
    if config.write_maps:
        artifacts.update(_write_maps(config.output_path.parent, tokenizer))

    manifest = {
        "tokenizer_path": str(config.tokenizer_path),
        "output": str(config.output_path),
        "format": config.output_format,
        "max_length": config.max_length,
        "pad_to_max_length": config.pad_to_max_length,
        "prepend_bos": config.prepend_bos,
        "append_eos": config.append_eos,
        "metrics": report,
        "samples": len(samples),
    }

    return EncodeResult(
        output_path=config.output_path,
        report_path=report_path,
        metrics=report,
        manifest=manifest,
        artifacts=artifacts,
    )


def _write_arrow(
    path: Path,
    sequences: list[list[int]],
    masks: list[list[int]],
    lengths: list[int],
    samples: list[CorpusSample],
) -> None:
    array_ids = pa.array(sequences, type=pa.list_(pa.int32()))
    array_masks = pa.array(masks, type=pa.list_(pa.int8()))
    array_lengths = pa.array(lengths, type=pa.int32())
    array_text = pa.array([sample.text for sample in samples], type=pa.string())
    table = pa.table(
        {
            "input_ids": array_ids,
            "attention_mask": array_masks,
            "length": array_lengths,
            "text": array_text,
        }
    )
    with pa.OSFile(str(path), "wb") as sink:
        with pa_ipc.new_file(sink, table.schema) as writer:
            writer.write_table(table)


def _write_maps(directory: Path, tokenizer: LoadedTokenizer) -> dict[str, str]:
    vocab_items = sorted(tokenizer.vocab.items(), key=lambda item: item[1])
    id2token_path = directory / "id2token.tsv"
    with id2token_path.open("w", encoding="utf-8") as handle:
        for token, idx in vocab_items:
            handle.write(f"{idx}\t{token}\n")
    token2id_path = directory / "token2id.json"
    token2id_path.write_text(json.dumps(dict(vocab_items), indent=2, ensure_ascii=False), encoding="utf-8")
    specials_path = directory / "special_tokens.json"
    specials_path.write_text(json.dumps(tokenizer.special_tokens, indent=2), encoding="utf-8")
    return {
        "id2token": str(id2token_path),
        "token2id": str(token2id_path),
        "special_tokens": str(specials_path),
    }


def _find_special_token(tokens: Iterable[str], candidates: set[str]) -> str | None:
    lowered = {token.lower(): token for token in tokens}
    for candidate in candidates:
        if candidate.lower() in lowered:
            return lowered[candidate.lower()]
    return None


__all__ = [
    "EncodeConfig",
    "EncodeResult",
    "LoadedTokenizer",
    "encode_dataset",
]

EncodeError = EncodingError

__all__.append("EncodeError")
